[package]
name = "spin-rust-hello"
version = "0.17.0"
authors = ["SpinKube Engineering Team"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
http = "0.2.9"
serde = { version = "1.0", features = ["derive"] }
spin-sdk = { git = "https://github.com/fermyon/spin", tag = "v2.0.1" }

[workspace]

[profile.release]
strip = true