spin_manifest_version = 2

[application]
authors = ["SpinKube Engineering Team"]
description = "A simple spin hello world"
name = "spin-hello"
version = "1.0.0"


[[trigger.http]]
route = "/hello"
component = "hello"

[[trigger.http]]
route = "/go-hello"
component = "go-hello"

[component.hello]
source = "target/wasm32-wasi/release/spin_rust_hello.wasm"

[component.hello.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.go-hello]
source = "go-hello/spin_go_hello.wasm"

[component.go-hello.build]
command = "cd go-hello && tinygo build -target=wasi -o spin_go_hello.wasm main.go && cd -"