name: build
on:
  workflow_call:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              os: "ubuntu-latest",
              arch: "x86_64",
            }
          - {
              os: "ubuntu-latest",
              arch: "aarch64"
            }
        shims: 
          - {
              name: "spin",
              version: "v2", 
            }
    env:
      ARCH: ${{ matrix.config.arch }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            "containerd-shim-* -> target"
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev
      - name: build ${{ matrix.shims.name }}
        run: |
          VERBOSE=1 make build SHIMS=${{ matrix.shims.name }}
      - name: unit tests ${{ matrix.shims.name }}
        run: |
          VERBOSE=1 make unit-tests  SHIMS=${{ matrix.shims.name }}
      - name: lowercase the runner OS name
        shell: bash
        run: |
          OS=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
          echo "RUNNER_OS=$OS" >> $GITHUB_ENV
      - name: package release assets
        run: |
          mkdir _dist
          cp target/${{ matrix.config.arch }}-unknown-linux-musl/release/containerd-shim-spin-${{ matrix.shims.version }} _dist/
          cd _dist
          tar czf containerd-shim-spin-${{ matrix.shims.version }}-${{ env.RUNNER_OS }}-${{ matrix.config.arch }}.tar.gz containerd-shim-spin-${{ matrix.shims.version }}
      - name: upload shim artifacts
        uses: actions/upload-artifact@v4
        with:
          name: containerd-shim-spin-${{ matrix.shims.version }}-${{ env.RUNNER_OS }}-${{ matrix.config.arch }}
          path: _dist/containerd-shim-spin-${{ matrix.shims.version }}-${{ env.RUNNER_OS }}-${{ matrix.config.arch }}.tar.gz
          retention-days: 5
