name: ci
on:
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            "containerd-shim-* -> target"
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev
      - name: fmt
        run: |
          make fmt
  build-wasm-images:
    uses: ./.github/workflows/docker-build-push.yaml
    with:
      test: true
  build:
    uses: ./.github/workflows/build.yaml
  publish-node-installer-image:
    uses: ./.github/workflows/node-installer.yaml
    needs: build
    # This action requires use of the GITHUB_TOKEN to publish the image
    # By default, PRs from forks don't have access, so we only run when the PR branch is on origin.
    if: ${{ ! github.event.pull_request.head.repo.fork }}
    with:
      ref: ${{ github.ref }}
  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      ARCH: x86_64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: azure/setup-kubectl@v4
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev
      - name: Extract containerd-shim-spin-linux-${{ env.ARCH }}
        run: |
          mkdir -p ./bin
          for f in containerd-shim-spin-*-linux-${{ env.ARCH }}/containerd-shim-spin-*-linux-${{ env.ARCH }}.tar.gz
            do tar -xzf "$f" -C ./bin
          done
      - name: install k3d
        run: make install-k3d
        working-directory: ./deployments/k3d
      - name: run integration tests
        run: BIN_DIR="./bin" make integration-tests

      - name: run collect debug logs
        if: failure()
        run: make tests/collect-debug-logs
 
      - name: upload debug logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: debug-logs
          path: debug-logs/
          retention-days: 5

      - name: clean up k3d
        if: always()
        run: make tests/clean
